language: node_js
node_js:
  - "0.10"
before_install:
  - gem install --no-rdoc --no-ri compass
install:
  - npm install
before_script:
  - gulp clean
script:
  - gulp
  - phantomjs test/extension/run.js